name: comment_trigger
jobs:
  pr_trigger:
    runs-on: ubuntu-latest
    if: github.event.comment.body == 'build' && ${{ github.event.issue.pull_request }}
    steps:
	  - name: Get PR SHA
        id: sha
        uses: actions/github-script@v4
        with:
            result-encoding: string
            script: |
              const { owner, repo, number } = context.issue;
              const pr = await github.pulls.get({
                owner,
                repo,
                pull_number: number,
              });
              return pr.data.head.sha
      - name: trigger_pr
        uses: actions/github-script@v4
        with:
            script: |
			  github.rest.actions.createWorkflowDispatch({
				owner,
				repo,
                workflow_id:'pr.yaml',
                ref:${{ steps.sha.outputs.result }}
			  });
on:
  issue_comment:
    types: [created, edited]